### ISSUE TITLE
GUI Freezes during file upload.

### ISSUE THREAD

**Issue by CYBERLUST** [Apathetic-Development-Team/spore#7]
This issue is related to how TKinter works. Each web requests will freeze the GUI and keep it locked until finished. Multi-threading will resolve this issue so that the GUI + Worker functions are not tied to the same thread.

**Comment by wwhtrbbtt** [comment]
Fixed in https://github.com/Apathetic-Development-Team/spore/pull/9, has to be merged.

**Comment by CYBERLUST** [comment]
Issue resolved, merged @wwhtrbbtt . Thanks.
